"""add user and skill relation

Revision ID: e88554300def
Revises: aa4d20c6b8eb
Create Date: 2025-11-27 11:38:22.268479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88554300def'
down_revision: Union[str, Sequence[str], None] = 'aa4d20c6b8eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userskilllink',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'skill_id')
    )
    op.create_foreign_key(None, 'exchange', 'user', ['receiver_id'], ['id'])
    op.create_foreign_key(None, 'exchange', 'user', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'exchange', 'skill', ['skill_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exchange', type_='foreignkey')
    op.drop_constraint(None, 'exchange', type_='foreignkey')
    op.drop_constraint(None, 'exchange', type_='foreignkey')
    op.drop_table('userskilllink')
    # ### end Alembic commands ###
